---
name: lando-seed-db-mysql
services:
  appserver:
    type: mysql
  db:
    type: mysql
    portforward: true
    creds:
      user: dba
      password: password
      database: example

tooling:
  mysql:
    service: db
    cmd: mysql -u root
  'db-import <file>':
    service: :host
    description: Imports a dump file into a database service
    cmd: /helpers/sql-import.sh
    options:
      host:
        description: The database service to use
        default: db
        alias:
          - h
      no-wipe:
        description: Do not destroy the existing database before an import
        boolean: true
